#!/usr/bin/env sh

$GAME_SOBEL/png2rgb.py png2rgb $GAME_SOBEL/baboon.png $GAME_SOBEL/baboon.rgb
java -cp $GAME_SOBEL/sobel.jar Sobel.RgbImage $GAME_SOBEL/baboon.rgb $GAME_SOBEL/output nrmse
echo "Sobel done ... (nrmse)"
#java -cp $GAME_SOBEL/sobel.jar Sobel.RgbImage $GAME_SOBEL/baboon.rgb $GAME_SOBEL/output psnr
#echo "Sobel done ... (psnr)"
$GAME_SOBEL/png2rgbAll.py rgb2png output/nrmse pngOutput/nrmse
echo "Rgb2Png done ... (nrmse)"
#$GAME_SOBEL/png2rgbAll.py rgb2png output/psnr pngOutput/psnr
#echo "Rgb2Png done ... (psnr)"
